# Generated by Django 3.2.6 on 2021-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='my_field',
            field=models.CharField(choices=[('a', 'Anime'), ('b', 'Football'), ('c', 'Framework'), ('d', 'Other')], max_length=1, null=True),
        ),
    ]
