# Generated by Django 3.2.6 on 2021-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_my_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='my_field',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Football', 'Football'), ('Framework', 'Framework'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
