# Generated by Django 3.2.6 on 2021-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_change_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
