# Generated by Django 3.2.6 on 2021-10-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_count',
            name='question_voted',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vote_count',
            name='voter',
            field=models.CharField(max_length=200),
        ),
    ]
